e57_input: true
e57_files:
  - C:\Users\zhhnl\OneDrive\_DashBoard\_BIMEngine\PointCloud\454 Natoma St - Nov 6\pointcloud_output_e57.e57
xyz_files:
  - output_xyz/454_Natoma_St.xyz
dilute: false
dilution_factor: 10
exterior_scan: false
pc_resolution: 0.002
grid_coefficient: 5

bfs_thickness: 0.3
tfs_thickness: 0.4

min_wall_length: 0.10
min_wall_thickness: 0.05
max_wall_thickness: 0.75
exterior_walls_thickness: 0.3

output_ifc: output_IFC/454_Natoma_St.ifc
ifc_project_name: 454 Natoma St
ifc_project_long_name: Point Cloud to BIM Conversion
ifc_project_version: version 1.0

ifc_author_name: User
ifc_author_surname: Name
ifc_author_organization: Organization

ifc_building_name: 454 Natoma St
ifc_building_type: Building
ifc_building_phase: As-Built

ifc_site_latitude: [37, 46, 48]
ifc_site_longitude: [-122, 24, 36]
ifc_site_elevation: 0.0

material_for_objects: Concrete